
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
import sys

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
	return ASSETS_PATH / Path(path)

def todo(user,password):
	print(user + "," + password)
	exit()

window = Tk()

window.geometry("1000x600")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
		window,
		bg = "#FFFFFF",
		height = 600,
		width = 1000,
		bd = 0,
		highlightthickness = 0,
		relief = "ridge"
		)

canvas.place(x = 0, y = 0)
canvas.create_text(
		492.0,
		96.99999999999994,
		anchor="nw",
		text="Sign In",
		fill="#000000",
		font=("Inter", 30 * -1)
		)

canvas.create_text(
		270.0,
		204.99999999999994,
		anchor="nw",
		text="User:",
		fill="#C4C4C4",
		font=("Inter", 30 * -1)
		)

canvas.create_text(
		187.0,
		299.99999999999994,
		anchor="nw",
		text="password:",
		fill="#c4c4c4",
		font=("inter", 30 * -1)
		)
if(sys.argv[1] == '1'):
	canvas.create_text(
			50.0,
			550.99999999999994,
			anchor="nw",
			text="error password and user don't match",
			fill="#FF0000",
			font=("inter", 30 * -1)
			)

entry_image_1 = PhotoImage(
		file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
		552.0,
		227.49999999999994,
		image=entry_image_1
		)
entry_1 = Entry(
		bd=0,
		bg="#C4C4C4",
		highlightthickness=0
		)
entry_1.place(
		x=367.0,
		y=201.99999999999994,
		width=370.0,
		height=49.0
		)

entry_image_2 = PhotoImage(
		file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
		552.0,
		322.49999999999994,
		image=entry_image_2
		)
entry_2 = Entry(
		bd=0,
		bg="#C4C4C4",
		highlightthickness=0
		)
entry_2.place(
		x=367.0,
		y=296.99999999999994,
		width=370.0,
		height=49.0
		)

button_image_1 = PhotoImage(
		file=relative_to_assets("button_1.png"))
button_1 = Button(
		image=button_image_1,
		borderwidth=0,
		highlightthickness=0,
		command=lambda: todo(entry_1.get(),entry_2.get()),
		relief="flat"
		)
button_1.place(
		x=431.0,
		y=396.99999999999994,
		width=231.0,
		height=82.0
		)

window.resizable(False, False)
window.mainloop()
